### ISSUE TITLE
Implement method for extracting users that commented on post(s) of a user

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#10]
- [ ] Implement method, should probably be added to the post-action, something like `PostGetCommenters`. Add in pagination functionality, like PostRetrieveByUser
- [ ] Write test
- [ ] Add an example to examples

**Comment by gocnik95** [comment]
Hello there, i would like to contribute on this issue, can u add me?

**Comment by stanvanrooy** [comment]
Awesome. I've typed up a quick doc on setting up a dev environment.

Once you've done that, you should be able to copy a large portion of the logic from PostRetrieveByUser.

Let me know if you get stuck on anything, I'm happy to assist.

**Comment by gocnik95** [comment]
hello there,

I'm trying to use created example get_user_id_from_username.py but the project is throwing KeyError: 'logged_in_user'. Only things that are changed in the file are username and password. Screenshot is in attachment. Could you give some ideas? if im doing wrong login or there is a deeper issue.
![image](https://user-images.githubusercontent.com/68646331/95992908-c1583500-0e2e-11eb-98e4-45873355861d.png)

**Comment by stanvanrooy** [comment]
Could you file a separate issue, and attach the debug output?

**Comment by stanvanrooy** [comment]
Added in c39a2203016e3cd7c590d24c1fe3ac088fe9e878
