### ISSUE TITLE
Implement method for extracting users that liked posts of a user

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#11]
- [ ] Implement method, should probably be added to the post-action, something like `PostGetLikes`. Add in pagination functionality, like PostRetrieveByUser
- [ ] Write test
- [ ] Add an example to examples

**Comment by juhas96** [comment]
Hey I want to contribute on this issue.

**Comment by stanvanrooy** [comment]
Awesome. I've typed up a [quick doc](https://github.com/stanvanrooy/instauto/blob/master/docs/dev_environment.md) on setting up a dev environment.

Once you've done that, you should be able to copy a large portion of the logic from `PostRetrieveByUser`. 

Let me know if you get stuck on anything, I'm happy to assist.

**Comment by juhas96** [comment]
Hey.

I'm trying to setup development environment. I installed Insta app from apkMirror and  BURP proxy on my phone also installed certificate on phone. How can I check if proxy is working correctly?

**Comment by stanvanrooy** [comment]
Install the postern app on your phone and try connecting it to the proxy.

If you see requests coming in, it works :)

**Comment by juhas96** [comment]
I have setupped postern. I can see requests from all apps except instragram. Also I have installed that app from description not original one. Do you have some special setup for postern for instagram?

**Comment by stanvanrooy** [comment]
No, there are no additional steps.

Do you see normal https requests in burp? You can try just going to google, or something like that.

**Comment by juhas96** [comment]
Yes, I see all requests, also from another apps, but from instagram any.

**Comment by stanvanrooy** [comment]
Could you try removing the app and following the guide here for installing it again? https://github.com/itsMoji/Instagram_SSL_Pinning

Could also be that you're on a newer version of Android and need to be rooted or something like that.

**Comment by juhas96** [comment]
Sure I let you know. I will try also emulator.

**Comment by juhas96** [comment]
@stanvanrooy do you have exact endpoint for getting likers of post? I',m trying media/{media_id}/likers ... but just getting 404 error

**Comment by stanvanrooy** [comment]
Will let you know asap. I'll check it out.

**Comment by juhas96** [comment]
Hey endpoint is fine, working now.

But how would you like to implement pagination? Because endpoint for feedByUser have next_max_id but likers doesn't have this property

**Comment by juhas96** [comment]
Hey, do you want specific data to extract from user, or I can return just User objects?

**Comment by stanvanrooy** [comment]
You can just return all data. Thanks

**Comment by stanvanrooy** [comment]
Added in #93
