### ISSUE TITLE
requests.cookies.CookieConflictError: There are multiple cookies with name, 'csrftoken'

### ISSUE THREAD

**Issue by Samu1808** [stanvanrooy/instauto#120]
**Describe the bug**
I found an bug that has to do with the the cookie csrftoken which is accidentally set twice.
It raises an error in the request package, which says that the cookie exists twice.

**To Reproduce**
1. I try to make an follow request => it works (200 response)
2. I try to unfollow the same user => it dont work => Multiple crsf_cookies Error

This a example code which raises the error:

![image](https://user-images.githubusercontent.com/64809910/101266726-13904500-3752-11eb-9f85-506e25a60125.png)

The weird thing about it is that sometimes it works espcially under Windows quite often compared to Linux.

**Debug output**
The error output:
Traceback (most recent call last):
  File "ia.py", line 167, in <module>
    resp = unfollow(client, user_id)
  File "ia.py", line 80, in unfollow
    return client.user_unfollow(f)
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/instauto/api/actions/friendships.py", line 20, in user_unfollow
    return self._friendships_act(obj)
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/instauto/api/actions/friendships.py", line 90, in _friendships_act
    obj.fill(self)
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/instauto/api/actions/structs/common.py", line 24, in fill
    setattr(self, k, func(client))
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/instauto/api/actions/structs/common.py", line 14, in <lambda>
    "_csrftoken": lambda c: c._session.cookies['csrftoken'],
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/pi/finspo/venv/lib/python3.8/site-packages/requests/cookies.py", line 396, in _find_no_duplicates
    raise CookieConflictError('There are multiple cookies with name, %r' % (name))
requests.cookies.CookieConflictError: There are multiple cookies with name, 'csrftoken'

Additional I added following code in the request/cookies.py script:
![image](https://user-images.githubusercontent.com/64809910/101266862-543c8e00-3753-11eb-95cd-8ff8bca7466e.png)

and this is the output of this:

Cookie: "Cookie csrftoken=**csrfcookie_value** for ", Name: csrftoken, Domain: , Path: /
To Return set: *censored*
Cookie: "Cookie ds_user=*censored* for ", Name: ds_user, Domain: , Path: /
Cookie: "Cookie ds_user_id=*censored* for ", Name: ds_user_id, Domain: , Path: /
Cookie: "Cookie mid=*censored* for ", Name: mid, Domain: , Path: /
Cookie: "Cookie rur=ASH for ", Name: rur, Domain: , Path: /
Cookie: "Cookie sessionid=*censored* for ", Name: sessionid, Domain: , Path: /
Cookie: "Cookie urlgen=*censored* for ", Name: urlgen, Domain: , Path: /
Cookie: "Cookie csrftoken=**csrfcookie_value** for .instagram.com", Name: csrftoken, Domain: .instagram.com, Path: /
toReturn exists value **csrfcookie_value**

Note that the **csrfcookie_value** is exactly the same, so the problem is that the cookie just is set twice, the value is correct and it would work othrwise.
Its also interesting that the second csrf_cookie has in contrast to the first cookie the domain attribute ".instagram.com".

**Additional context**
I really hope some of you has an idea what the problem could be or came along with the same error.
Please try it yourself and try to debug it, especially if you make multiple follows or unfollows.
And as I said sometimes it works quite fine, but sometimes I get this error.

**Comment by stanvanrooy** [comment]
Hmm, that is a weird error. 

Are you instantiating the client from a save file?

**Comment by Samu1808** [comment]
Yes exactly and when i deleted it it again works first.

**Comment by Samu1808** [comment]
And as I said I get this error mostly on Linux, I for example executed the same script with the same save file on windows and it worked. But I reproduced the same error also under windows, but in Linux it never worked for me.
And i think important is also that the first request works fine.

**Comment by stanvanrooy** [comment]
I'm suspecting this has something to do with the way the `requests.Session` gets recreated from the save file. 

I'll check this out tomorrow.
