### ISSUE TITLE
[Question] Using instauto inside VPS

### ISSUE THREAD

**Issue by Anteeiiku** [stanvanrooy/instauto#122]
Hello, I’m interested in this project and I have a question. It is possible to run instauto on VPS without getting ban or something like that? If yes what I’ll need? And if I cannot run it on VPS, Any suggestions where I can run it 24 hours without using my computer?

Thanks and keep going.

**Comment by stanvanrooy** [comment]
Hello,

That should be possible. `Instauto` tries to mimic the behaviour of the Instagram as closely as possible, which should help. But just like with any other app, you should watch your limits. 

Running on a VPS is possible, but I think Instagram nowadays catches on fairly quickly. I suggest running it with a proxy.

Are you planning on implementing something yourself with the API wrapper, or using the `instauto.Bot` class?

**Comment by Anteeiiku** [comment]
Hello, thanks for responding. I'm using it to upload posts only. So I think it's an API wrapper 😁

**Comment by stanvanrooy** [comment]
Ahh, okay. You should probably use the `instauto.helpers.post.upload_image_to_feed` function for that.

I don't think you'll run into any major problems.

**Comment by stanvanrooy** [comment]
lmk if there's anything else.

**Comment by Anteeiiku** [comment]
Hello there, 
Finally I have finished my university semester so I'm free now lol.
I have been searching how to implement the proxy using instauto  but I didn't find any answer and did looking for the login structure and didn't find anything related to proxy.
