### ISSUE TITLE
Implement change password feature

### ISSUE THREAD

**Issue by LordArma** [stanvanrooy/instauto#125]
Hello. It's me again!

Currently Instagram may block some features in an account if it think account's owner use private API. You can change the account's password and after it Instagram will unblock your account.

What if we can change password from the API? So we can automatically change the password in the period of times and prevent our account from being block soon.

May you add changing password feature in the future?

**Comment by stanvanrooy** [comment]
See https://github.com/stanvanrooy/instauto/blob/master/examples/profile/update_password.py
