### ISSUE TITLE
example shows errors

### ISSUE THREAD

**Issue by s0rnix** [stanvanrooy/instauto#126]
Hi, I am quite new. 

Sorry for my post. 
Iam want to post some generated picutre from my raspberry to instagram.

I installed your api with "pip install instauto".

If iam running folling example script:

> #!/usr/bin/env python
> import os
> 
> from instauto.api.client import ApiClient
> from instauto.api import structs as st
> from instauto.api.actions import post as ps
> 
> if __name__ == '__main__':
>     if os.path.isfile('./.instauto.save'):
>         client = ApiClient.initiate_from_file('./.instauto.save')
>     else:
>         client = ApiClient(user_name=os.environ.get("INSTAUTO_USER") or "myinstname", password=os.environ.get("INSTAUTO_PASS") or "myinstapw")
>         client.login()
>         client.save_to_disk('./.instauto.save')
> 
>     post = ps.PostFeed(
>         path='./test.jpg',
>         caption='This is an example. Follow me!'
>     )
>     resp = client.post_post(post, 80)
>     print("Success: ", resp.ok)

i get following error:

> user@raspberrypi:/home/userr/inst# ./postinsta.py
> Traceback (most recent call last):
>   File "./postinsta.py", line 4, in <module>
>     from instauto.api.client import ApiClient
>   File "/usr/local/lib/python2.7/dist-packages/instauto/api/client.py", line 35
>     def __init__(self, ig_profile: IGProfile = None, device_profile: DeviceProfile = None, state: State = None,
>                                  ^
> SyntaxError: invalid syntax

same with the example like script:

> from instauto.api.client import ApiClient
> from instauto.api.actions import post as ps
> 
> if __name__ == '__main__':
>     client = ApiClient("myinstaname", "myinstapw")
>     client.login()
> 
>     like = ps.Like(
>         media_id="2459763797153350874"
>     )
>     client.post_like(like)

Error:

> user@raspberrypi:/home/user/inst# python like2.py
> Traceback (most recent call last):
>   File "like2.py", line 1, in <module>
>     from instauto.api.client import ApiClient
>   File "/usr/local/lib/python2.7/dist-packages/instauto/api/client.py", line 35
>     def __init__(self, ig_profile: IGProfile = None, device_profile: DeviceProfile = None, state: State = None,
>                                  ^
> SyntaxError: invalid syntax

kind regards :)

**Comment by stanvanrooy** [comment]
Hey :) No problem at all, the opposite of it even, thanks for the report.

I'll try and look into this tomorrow.

In the meantime, could you try downgrading to `instauto` 1.0.2? (`pip install instauto==1.0.2`.

If the package is of any help to you, please consider starring the repo :)

**Comment by s0rnix** [comment]
thanks you.

i have downgraded successfully..

> pip install instauto==1.0.2
> ...
> ...
> ...
> Installing collected packages: instauto
>   Found existing installation: instauto 1.0.3
>     Uninstalling instauto-1.0.3:
>       Successfully uninstalled instauto-1.0.3
> Successfully installed instauto-1.0.2

but get the same error:


user@raspberrypi:/home/user/inst# cat like2.py
from instauto.api.client import ApiClient
from instauto.api.actions import post as ps

if __name__ == '__main__':
    client = ApiClient("myinstauser", "myinstapw")
    client.login()

    like = ps.Like(
        media_id="2459763797153350874"
    )
    client.post_like(like)

user@raspberrypi:/home/user/inst# python like2.py
Traceback (most recent call last):
  File "like2.py", line 1, in <module>
    from instauto.api.client import ApiClient
  File "/usr/local/lib/python2.7/dist-packages/instauto/api/client.py", line 35
    def __init__(self, ig_profile: IGProfile = None, device_profile: DeviceProfile = None, state: State = None,
                                 ^
SyntaxError: invalid syntax

where the small arrow behind ig_profile points to the colon

Sorry. This editor shows the source code not correctly. i copied this lines to pastebin to

https://pastebin.com/xxEXDajX

**Comment by stanvanrooy** [comment]
Are you using python3.6+?

**Comment by s0rnix** [comment]
iam using  Python 2.7.13 

should i use Python 3?

**Comment by stanvanrooy** [comment]
`Instauto` is 3.6+. That should fix it.

**Comment by s0rnix** [comment]
now it´s working. thanks.
