### ISSUE TITLE
account getting banned

### ISSUE THREAD

**Issue by alexferra** [stanvanrooy/instauto#127]
![image](https://user-images.githubusercontent.com/14792671/101678624-2e9dd600-3a2c-11eb-9ed6-61df14a77aa8.png)

**Comment by stanvanrooy** [comment]
How often are you performing the action?

**Comment by alexferra** [comment]
its random, from 10 minutes to two hours sleep

**Comment by stanvanrooy** [comment]
Okay. Luckily, the error is pretty descriptive. `SingleSessionMultipleDevice` indicates that something is going wrong when refreshing the session.

This should've been fixed in 1.0.3. Which version are you using?

**Comment by stanvanrooy** [comment]
Caught another usage of the wrong id. Thanks for reporting the issue, and I'm sorry the package got your account limited.
