### ISSUE TITLE
Implement method for getting following_count and follower_count

### ISSUE THREAD

**Issue by tibotix** [stanvanrooy/instauto#142]
**Is your feature request related to a problem? Please describe.**
I would like to have a function that needs only one call to IG API to get the current `following_count` and `followers_count` of an user, meaning how many follower a user have and how many other people the user follows.

As far as i know this currently can be done by getting all following/followers with pagination through `client.followers_get(GetFollowers(user_id=xxxxx))` and count them all.
This is useful if you want to get explicit all user **objects**, but if you only want to know how many following/follower a user has this would completely flood IG API with pagination calls.

**Describe the solution you'd like**
I have thought about something similar to this:
`client.followers_count_get(GetFollowersCount(user_id=xxxx))`

**Additional context**
-

**Comment by stanvanrooy** [comment]
The profile dict returned by `profile_info` should contain two attributes `follower_count` and `following_count` or something like that.

See  https://www.github.com/stanvanrooy/instauto/tree/master/examples%2Fprofile%2Fprofile_info.py

**Comment by tibotix** [comment]
Oh. I see. Okay, thank you. I overlooked that method.

**Comment by stanvanrooy** [comment]
No problem at all. Let me know if there's anything else I can help with.
