### ISSUE TITLE
Accounts with two-factor authentication turned on can't be logged in.

### ISSUE THREAD

**Issue by hmdz105** [stanvanrooy/instauto#143]
**Describe the bug**
When 2FA is turned on in an instagram account, the app faces an error when trying to log in:

**To Reproduce**
Run the following code

```python
import os

from instauto.api.client import ApiClient
from instauto.api import structs as st
from instauto.api.actions import post as ps

if os.path.isfile('./.instauto.save'):
    client = ApiClient.initiate_from_file('./.instauto.save')
else:
    client = ApiClient(user_name="username", password="password")
    client.login()
    client.save_to_disk('./.instauto.save')
```

Assuming the app has no previous saved session, the new login fails with this error:
```
Traceback (most recent call last):
  File "G:\DB\Dropbox\instagramPrjct\Initial tests-v0.2\InstagramUploader.py", line 38, in <module>
    client.login()
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\authentication.py", line 64, in login
    resp = self._request('accounts/login/', Method.POST, data=data2, signed=True)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 233, in _request
    self._check_response_for_errors(resp)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 274, in _check_response_for_errors
    raise BadResponse("Received a non-200 response from Instagram")
instauto.api.exceptions.BadResponse: Received a non-200 response from Instagram
```

**Expected behavior**
The console should ask for the 2FA code. After manual entry, the log in should succeed and the bot continue working.

**Additional context**
I used another library called "instabot" and it asked for 2FA then logged in. Unfortunately the library is outdated and no longer maintained, and many of its endpoints no longer work.

**Comment by stanvanrooy** [comment]
You can now either pass in a `_2fa_function` argument to the constructor of `ApiClient`, or just type the code in to the terminal.

The `_2fa_function` should be a callable that receives the username as input and returns the 2fa code as output.

**Comment by hmdz105** [comment]
Excellent job! Thanks for the quick fix!

**Comment by stanvanrooy** [comment]
Let me know if there's anything else missing from instauto :)

Hamed schreef op 2021-02-18 09:51:

**Comment by hmdz105** [comment]
I can't still find a way to upload videos. Sending videos to posts, stories and also in carousel format would be very handy.
