### ISSUE TITLE
retrieve by short link/media id

### ISSUE THREAD

**Issue by hawaiiH** [stanvanrooy/instauto#153]
Your instauto project is really useful and cool.
In this thread https://github.com/stanvanrooy/instauto/issues/33 you've implemented cool functions - retrieve by short id/media id. Links to examples are not working. And I couldn't find anything related to this functions.
Is it still possible to use them?

P.S.: also found that `Username` and `RetrieveByUser` haven't got method `create`, instead you can pass variables directly, but they are in the examples still.

**Comment by stanvanrooy** [comment]
All dataclasses should be initiated using the constructor. `Create` isn't used anymore. Some examples may be outdated, feel free to submit a pr that updates them ;)

Regarding the `post_retrieve_by_id` & `post_retrieve_by_short_id`, they do not exist anymore. Not sure why, I'll add them back in today :)

**Comment by stanvanrooy** [comment]
@hawaiiH is there anything else missing from `instauto` right now? I'm currently working on a large rewrite(largely done), and I'd like to implement as many new features as possible, while I'm at it :)

**Comment by hawaiiH** [comment]
For my work `post_retrieve_by_short_id` would be needed :)

**Comment by hawaiiH** [comment]
For my work post_retrieve_by_short_id would be needed :) Reply to comment - is a nice a feature. In the rest it's fully responding to my needs.
