### ISSUE TITLE
story seen method

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#163]
it would be great if you add a method that simulate story seen process 
for example user A (that use instauto) seen stories of user B (any other user) and user B can see user A in his watchlist 
in other libs like instagram_private_api user A can fully access (taken time , media , id and ... ) and even download other users stories but user B does not have user A in his/her watchlist

again sorry for hard speaking

**Comment by stanvanrooy** [comment]
Could you clarify? With that library, you can watch stories of accounts that you don't follow?

**Comment by phlaskoo** [comment]
> Could you clarify? With that library, you can watch stories of accounts that you don't follow?

No with that library I can access stories of users that I follow but that users can not see me on his/her watch list

For example imagine that I follow you on ig and you post a story 
Then I log in with instagram_private_api and I can access all your story data (time,media,id) but you do not have my account name on your story watch list

**Comment by stanvanrooy** [comment]
Aha, that makes sense. Could you maybe provide a few more details on how instagram_private_api`does that?
