### ISSUE TITLE
Ensure all examples work.

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#165]
Some of the examples are outdated. This should be fixed. Let's compose a list of non-working examples here.

Most of them, at least on first sight, do not work, because they still use the old `username` param, instead of `user_name`.

List:

- examples/direct/*
- examples/friendships/*
- examples/profile/*
- examples/search/get_user_id_from_ username.py
 -examples/post/comment_post.py
- examples/post/like_post.py
- examples/post/post_get_commeters.py
- examples/post/post_get_likers.py
- examples/post/post_retrieve_by_tag.py
- examples/post/post_retrieve_by_user.py
- examples/post/save_post.py
- examples/post/unlike_post.py
- examples/post/upload_carousel_fo_feed.py
- examples/post/upload_carousel_with_usertags_to_feed.py
- examples/post/upload_image_to_feed.py
- examples/post/upload_image_to_story.py
- examples/post/upload_image_with_location_to_feed.py 
- examples/post/upload_image_with_usertag_to_feed.py

**Comment by lsergei** [comment]
@stanvanrooy , after looking at majority of examples, most require an easy fix. However for update_picture.py (updates profile picture) I couldn't find a solution:

```
$ python3 update_picture.py
Traceback (most recent call last):
  File "../update_picture.py", line 17, in <module>
    post = ps.PostNull(
AttributeError: module 'instauto.api.actions.structs.post' has no attribute 'PostNull'

```

My packages/versions:

```
Package       Version
------------- ---------
APScheduler   3.7.0
certifi       2020.12.5
chardet       4.0.0
idna          2.10
imagesize     1.2.0
instauto      1.0.6
orjson        3.5.2
pip           21.1.1
protobuf      3.15.8
pycryptodomex 3.10.1
pytz          2021.1
requests      2.25.1
setuptools    56.0.0
six           1.15.0
tzlocal       2.1
urllib3       1.26.4
wheel         0.36.2
```

Could you kindly help with this one please?

**Comment by stanvanrooy** [comment]
The update profile picture functionality was introduced after the last release (1.0.6). We can skip that one, for now.

**Comment by lsergei** [comment]
> The update profile picture functionality was introduced after the last release (1.0.6). We can skip that one, for now.

thank you @stanvanrooy . Is there any way I can test it before the release?

**Comment by stanvanrooy** [comment]
Yes, you can install the latest version directly from the repo: `pip install git+https://github.com/stanvanrooy/instauto.git`
