### ISSUE TITLE
followers_get and followings_get limit

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#167]
these two methods do not retrieve more than 100 users , weird as in retrieve post limit in  #162 
again i think it is a pagination problem

**Comment by phlaskoo** [comment]
> What version are you using?

Latest version on github

**Comment by stanvanrooy** [comment]
Same with this one. I can't reproduce the issue. 

Would it be possible for you, to post a few more details? I.e. are you getting any errors? How do you set up the `ApiClient` instance? Which account are you trying to retrieve posts from? How many posts does the user have? Is it a private or public account?
