### ISSUE TITLE
Getting Error On Running Example Of  "upload_carousel_to_feed.py"

### ISSUE THREAD

**Issue by ThisIsBBBGithubAc** [stanvanrooy/instauto#168]
Hi, At first, thanks for providing such a great package. But i guess there is an  issue because when i installed the V2.0.0 of Instauto and tried to run the example of [https://github.com/stanvanrooy/instauto/blob/master/examples/post/upload_carousel_to_feed.py](url) without putting user id for tagging
like this

```
import os
from decouple import config 
from instauto.api.client import ApiClient
from instauto.api.actions import post as ps

if __name__ == '__main__':
    INSTA_USERNAME = os.environ.get('INSTA_USERNAME')
    INSTA_PASSWORD = os.environ.get('INSTA_PASSWORD')

    if os.path.isfile('./.instauto.save'):
        client = ApiClient.initiate_from_file('./.instauto.save')
    else:
        client = ApiClient(username=INSTA_USERNAME, password=INSTA_PASSWORD)
        client.log_in()
        client.save_to_disk('./.instauto.save')
 

    usertag1 = ps.UserTag(
        user_id="",     # user_id of user you want to tag
        x=0.2,          # relative x coordinate with 0<=x<=1, with 0 for left and 1 for right
        y=0.2           # relative y coordinate with 0<=x<=1, with 0 for top and 1 for bottom
    )
    usertags = ps.UserTags(
        usertags=[usertag1]
    )

    posts = [
        ps.PostFeed(
            path='/home/AP/InstaPost/8b75115a/photo1.jpg',
            caption='This is an example. Follow me!',
            usertags=usertags
        ),
        ps.PostFeed(
            path='/home/AP/InstaPost/8b75115a/photo2.jpg',
            caption='Another post',
            usertags=usertags
        )
    ]

    resp = client.post_carousel(posts, "Caption", 80)
    print("Success: ", resp['configure_sidecar'].ok)

```

but getting the below error:

>  Traceback (most recent call last):
>   File "pc.py", line 28, in <module>
>     usertag1 = ps.UserTag(
> AttributeError: module 'instauto.api.actions.post' has no attribute 'UserTag'

And when i tried to run the code without putting "usertags=usertags" on PostFeed() as shown below

```
import os
from decouple import config 
from instauto.api.client import ApiClient
from instauto.api.actions import post as ps

if __name__ == '__main__':
    INSTA_USERNAME = os.environ.get('INSTA_USERNAME')
    INSTA_PASSWORD = os.environ.get('INSTA_PASSWORD')

    if os.path.isfile('./.instauto.save'):
        client = ApiClient.initiate_from_file('./.instauto.save')
    else:
        client = ApiClient(username=INSTA_USERNAME, password=INSTA_PASSWORD)
        client.log_in()
        client.save_to_disk('./.instauto.save')
 
    posts = [
        ps.PostFeed(
            path='/home/AP/InstaPost/8b75115a/photo1.jpg',
            caption='This is an example. Follow me!'
        ),
        ps.PostFeed(
            path='/home/AP/InstaPost/8b75115a/photo2.jpg',
            caption='Another post'
        )
    ]

    resp = client.post_carousel(posts, "Caption", 80)
    print("Success: ", resp['configure_sidecar'].ok)
```

i got this error:

> Traceback (most recent call last):
>   File "pc.py", line 50, in <module>
>     resp = client.post_carousel(posts, "Caption", 80)
>   File "/home/AP/env4bbb/lib/python3.8/site-packages/instauto/api/actions/post.py", line 153, in post_carousel
>     self._add_user_tags(data, post.user_tags is hasattr(post, 'user_tags'))
>   File "/home/AP/env4bbb/lib/python3.8/site-packages/instauto/api/actions/post.py", line 169, in _add_user_tags
>     user_tags = user_tags.to_dict()
> AttributeError: 'bool' object has no attribute 'to_dict'

**Comment by stanvanrooy** [comment]
`from instauto.api.actions import post as ps` should be `from instauto.api.actions.structs.ps`.  Some of the examples are a bit of outdated, see https://github.com/stanvanrooy/instauto/issues/165 :)
