### ISSUE TITLE
client.save_to_disk error

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#178]
client.save_to_disk save an empty .save file that cannot be parsed in next uses

coded as example

**Comment by takahori004** [comment]
If you are using Windows, you can solve the problem by changing the following.

instauto/api/client.py  : line 121

f = open (file_name, "w" if not overwrite else "w +", encoding = "utf-8")

* add encoding

**Comment by stanvanrooy** [comment]
> If you are using Windows, you can solve the problem by changing the following.
> 
> instauto/api/client.py : line 121
> 
> f = open (file_name, "w" if not overwrite else "w +", encoding = "utf-8")
> 
>     * add encoding

Great that that fixes it for you! Do you have any explanation for why the error happens, and why this fixes it?
