### ISSUE TITLE
Make a report function

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#180]
Make a function to report a post or story
Sometimes it is needed ...

**Comment by stanvanrooy** [comment]
How would something like this look for you, in an ideal situation? Instagram offers quite a few  (nested) report options, which can be difficult to implement in a clear way.

**Comment by phlaskoo** [comment]
> How would something like this look for you, in an ideal situation? Instagram offers quite a few (nested) report options, which can be difficult to implement in a clear way.

One part of my code is to look tags same as my post tags to see who used my post without mentioning me and reporting them I want to use it for this purpose

**Comment by stanvanrooy** [comment]
How do you report the post? As spam? Or something else?

**Comment by phlaskoo** [comment]
> How do you report the post? As spam? Or something else?

With Something else to mention the reason or property violence or even fraud

**Comment by stanvanrooy** [comment]
closing this, as this is not really the direction I want to go in with this package
