### ISSUE TITLE
Client post returns true but doesnt upload post

### ISSUE THREAD

**Issue by aidanMiklos** [stanvanrooy/instauto#194]
When using client.post_post() and checking with ok() the function returns success True but does not post the image. It was working earlier but has recently stopped. **Code Below** 

```
import os
import time
from PIL import Image
from instauto.api.client import ApiClient
from instauto.api import structs as st
from instauto.api.actions import post as ps
import logging
logging.basicConfig()
logging.getLogger('').setLevel(logging.DEBUG)

def post(path, delay):
  time.sleep(delay)
  if os.path.isfile('./.instauto.save'):
      client = ApiClient.initiate_from_file('./.instauto.save')
  else:
      client = ApiClient(username="USERNAME", password="PASSWORD")
      try:
        client.log_in()
      except:
        return "Cant log in"
      client.save_to_disk('./.instauto.save')
      

  post = ps.PostFeed(
      path=path,
      caption=""
  )
  resp = client.post_post(post, 80)
  return("Success: ", resp.ok)
```

Before it stopped working it would return the same message but upload the image. 

**DEBUG BELOW**

`INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "AuthenticationMixin._refresh_session" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-07-31 22:41:12.397404+00:00 (in 380.458888 seconds)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com:443
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "GET /api/v1/zr/token/result/?device_id=android-30f84f16abfc72dd&token_hash=&custom_device_id=b018f434-30f8-4f16-abfc-72dd7f680819&fetch_reason=token_expired HTTP/1.1" 200 193
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/qe/sync/ HTTP/1.1" 200 582
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:discord.gateway:Keeping shard ID None websocket alive with sequence 6.
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /rupload_igphoto/1627834524_0_2399810549 HTTP/1.1" 200 61
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 200 1607`

Thank you for taking a look

**Comment by stanvanrooy** [comment]
- What are the dimensions of the image you're trying to upload?
- What is the response content returned by Instagram (`resp.content`)?

**Comment by aidanMiklos** [comment]
I changed the ip of the server and retried the image today and it worked. I think maybe I was blacklisted by Instagram or I was wondering does your api have a limit to the number of images uploaded?

**Comment by aidanMiklos** [comment]
File "/home/runner/Slave/continuousbot.py", line 32, in continuousBot
    instbot.start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/bot.py", line 110, in start
    accounts = self.input.filtered_accounts
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 92, in filtered_accounts
    return list(filter(lambda x: x['id'] not in seen and seen.append(x['id']) is None, self._accounts))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 92, in <lambda>
    return list(filter(lambda x: x['id'] not in seen and seen.append(x['id']) is None, self._accounts))
TypeError: 'User' object is not subscriptable

**Comment by stanvanrooy** [comment]
Is this related to this issue?
