### ISSUE TITLE
Fetch stories

### ISSUE THREAD

**Issue by javad94** [stanvanrooy/instauto#196]
**Is your feature request related to a problem? Please describe.**
Thanks for this great library. I checked the documentation and haven't found a method to fetch and mark seen on user's stories.

**Describe the solution you'd like**
It would be good to add methods for fetching and marking seen on stories.

**Additional context**

**Comment by stanvanrooy** [comment]
This has been released in v2.0.3. Examples on how to use:
- api: https://github.com/stanvanrooy/instauto/blob/master/examples/api/post/retrieve_story.py
- helpers: https://github.com/stanvanrooy/instauto/blob/master/examples/helpers/post/retrieve_stories_from_user.py

**Comment by javad94** [comment]
> This has been released in v2.0.3. Examples on how to use:
> 
> * api: https://github.com/stanvanrooy/instauto/blob/master/examples/api/post/retrieve_story.py
> * helpers: https://github.com/stanvanrooy/instauto/blob/master/examples/helpers/post/retrieve_stories_from_user.py

Great. Thank you.
