### ISSUE TITLE
User object is not sub scriptable

### ISSUE THREAD

**Issue by aidanMiklos** [stanvanrooy/instauto#202]
When running the like() and follow() functions followed by start() this error occurs.

'File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop await self.coro(*args, **kwargs) File "/home/runner/SlaveSpammer-1/dcbot.py", line 20, in calling bruh() File "/home/runner/SlaveSpammer-1/instagram.py", line 30, in bruh spammer.start() File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/bot.py", line 115, in start accounts = self.input.filtered_accounts File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 91, in filtered_accounts return list(filter( File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 92, in <lambda> lambda x: x['id'] not in seen and seen.append(x['id']) is None, TypeError: 'User' object is not subscriptable'

**Comment by stanvanrooy** [comment]
released in v2.0.5
