### ISSUE TITLE
KeyError: 'challenge'

### ISSUE THREAD

**Issue by wyoko** [stanvanrooy/instauto#214]
I have a problem with adding a post. Usually, posts are added normally, but sometimes I get this error:
logs: [https://pastebin.com/M4w1t7QL](https://pastebin.com/M4w1t7QL)
password for logs: VpPyhhVeDK

**Comment by stanvanrooy** [comment]
I've just published a new version with additional logging. Could you try reproducing it while running the latest version?

Note: you'll need to set the logging level to debug for the message to show up.
