### ISSUE TITLE
`_post_post` doesn't work.

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#28]
Fails with `{'message': 'Missing info.', 'status': 'fail'}`. To reproduce:
```python
obj = pst.Post.create(path='./to_upload.png', source_type=WhereToPost.Feed, caption="Hey!")
resp = self._client.post_post(obj, quality=100)
resp_as_json = resp.json()
self.assertTrue(resp_as_json['status'] == 'ok')
```

**Comment by sanderbakker** [comment]
Has this issue been resolved? I'm getting the same error as we speak when executing this code

**Comment by stanvanrooy** [comment]
Could you file a new issue, with the steps to reproduce your issue? I'll take a look at it asap.

**Comment by stanvanrooy** [comment]
@sanderbakker Following up on this. Without repro steps I can't do much.

**Comment by sanderbakker** [comment]
I will make a separate issue but the steps to reproduce are literally
copying the example and executing it
