### ISSUE TITLE
Don't work method upload photo

### ISSUE THREAD

**Issue by markdrrr** [stanvanrooy/instauto#32]
**Hello, i use your code from examples** (https://github.com/stanvanrooy/instauto/blob/master/examples/post/upload_image.py)
**I got error** AttributeError: module 'instauto.api.actions.structs.post' has no attribute 'Post'

**Comment by stanvanrooy** [comment]
The examples were updated - those updates weren't reflected yet in the latest release. Please run `pip install --upgrade instauto` and try again.

**Comment by stanvanrooy** [comment]
But be aware of #28. You can subscribe to the issue to receive a notification once I've had the time to debug that and fix it.

**Comment by markdrrr** [comment]
Cool, that work)) 
Last question, how add location with upload post ?
