### ISSUE TITLE
Questions about methods and their implementation 

### ISSUE THREAD

**Issue by markdrrr** [stanvanrooy/instauto#33]
**This is a very cool project**, I'm glad I found you. I have a couple of questions:
**1.** What method should you use to get information about a post from a short link?
 How to get this information, including media files.
**2.** What method should you use to post a comment and how to use it correctly?
**3.** How to correctly compose a request for uploading a photo with geolocation ?

I would be very grateful if I get an answer.

**Comment by markdrrr** [comment]
@stanvanrooy can you help how to do this?

**Comment by stanvanrooy** [comment]
> **1.** What method should you use to get information about a post from a short link?
> How to get this information, including media files.

I'm pretty sure this functionality hasn't been implemented yet. Instauto is a work in progress. Could you elaborate a bit more on what exactly you mean with this? So I can shorttrack it.
> **2.** What method should you use to post a comment and how to use it correctly?

See https://www.github.com/stanvanrooy/instauto/tree/master/examples%2Fpost%2Fcomment_post.py
> **3.** How to correctly compose a request for uploading a photo with geolocation ?

I'll add an example of this in a few hours. Will update this comment with the link, once it's pushed to the repo.

**Comment by markdrrr** [comment]
@stanvanrooy How get media_id from short link. example https://www.instagram.com/p/CEv1aMcJq5J/

**Comment by markdrrr** [comment]
> > **1.** What method should you use to get information about a post from a short link?
> > How to get this information, including media files.
> 
> I'm pretty sure this functionality hasn't been implemented yet. Instauto is a work in progress. Could you elaborate a bit more on what exactly you mean with this? So I can shorttrack it.

I mean that
Use the short link "https://www.instagram.com/p/CEv1aMcJq5J/" to get information about the publication, for example:
author of the post, description, geolocation, media file, number of likes, comments

**Comment by stanvanrooy** [comment]
@markdrrr for posting with location data, see https://github.com/stanvanrooy/instauto/blob/master/examples/post/upload_image_with_location.py. 

Note: I haven't tested posting with location, if you could test this would be great. If it indeed doesn't work, you could try replacing the `location = ....` line with these ones:
1: ```location = ps.Location(name="The white house")```
2: ```location = ps.Location(address="1600 Pennsylvania Avenue NW, Washington, DC 20500, United States")```

Let me know if those also don't work.

**Comment by stanvanrooy** [comment]
> > > **1.** What method should you use to get information about a post from a short link?
> > > How to get this information, including media files.
> > 
> > 
> > I'm pretty sure this functionality hasn't been implemented yet. Instauto is a work in progress. Could you elaborate a bit more on what exactly you mean with this? So I can shorttrack it.
> 
> I mean that
> Use the short link "https://www.instagram.com/p/CEv1aMcJq5J/" to get information about the publication, for example:
> author of the post, description, geolocation, media file, number of likes, comments

That is indeed not implemented yet, but it should be relatively easy to add in. I'll probably do that tomorrow, I'll tag you when it's released.

**Comment by markdrrr** [comment]
@stanvanrooy i tried all the options you suggested, they don't work (((
Every time a bug:
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Location is not JSON serializable

P.S. How get media_id from short link, example https://www.instagram.com/p/CEv1aMcJq5J/ ???

**Comment by stanvanrooy** [comment]
Thanks. Will check.

> P.S. How get media_id from short link, example https://www.instagram.com/p/CEv1aMcJq5J/ ???

See the comment above.

**Comment by markdrrr** [comment]
> See the comment above.

I have not found an example of how to find the media id in the publication...

**Comment by stanvanrooy** [comment]
> That is indeed not implemented yet, but it should be relatively easy to add in. I'll probably do that tomorrow, I'll tag you when it's released. Also, if you like the library, consider giving it a star :)

**Comment by markdrrr** [comment]
Sorry, I got it

**Comment by stanvanrooy** [comment]
@markdrrr See the following links for updated examples:

https://github.com/stanvanrooy/instauto/blob/master/examples/post/post_retrieve_by_short_id.py
https://github.com/stanvanrooy/instauto/blob/master/examples/post/upload_image_with_location.py
https://github.com/stanvanrooy/instauto/blob/master/examples/post/post_retrieve_by_media_id.py

You'll need to install the latest version from github: `pip install git+git://github.com/stanvanrooy/instauto.git`
