### ISSUE TITLE
Don't work comment_post

### ISSUE THREAD

**Issue by markdrrr** [stanvanrooy/instauto#35]
My code: 
```
import os

from instauto import ApiClient
from instauto import post as ps

if __name__ == '__main__':
    if os.path.isfile('./.instauto.save'):
        client = ApiClient.initiate_from_file('./.instauto.save')
    else:
        client = ApiClient(user_name="your_username", password="your_password")
        client.login()
        client.save_to_disk('./.instauto.save')

    like = ps.Comment.create(
        media_id="1734612737423614055_6400760974",
        comment_text="Such great!"
    )
    resp = client.post_comment(like)
    print("Success: ", resp.ok)
```

**return "Success:  False"
no comment is sent**

How to get media ID from a normal link? example https://www.instagram.com/p/CEukJmYgQxD/

**Comment by stanvanrooy** [comment]
Have you updated the username and password? Are you following the account that posted the image?

**Comment by markdrrr** [comment]
> Have you updated the username and password? Are you following the account that posted the image?

@stanvanrooy yes i added my data username and password
This post is from my account
