### ISSUE TITLE
API No longer logging in

### ISSUE THREAD

**Issue by marvic2409** [stanvanrooy/instauto#41]
I get the following error when trying to run the login code flow:
`Traceback (most recent call last):
  File "insta.py", line 158, in <module>
    main()
  File "insta.py", line 48, in main
    getsubnums()
  File "insta.py", line 55, in getsubnums
    client.login()
  File "/home/user/anaconda3/lib/python3.8/site-packages/instauto/api/actions/authentication.py", line 64, in login
    self.state.logged_in_account_data = LoggedInAccountData(**resp.json()['logged_in_user'])
KeyError: 'logged_in_user'
`

**Comment by marvic2409** [comment]
And it seems I have discovered what 100+ requests in a second will do

**Comment by stanvanrooy** [comment]
This happens sometimes when logging in from a saved file. Could you share the code you use to initiate the client?

**Comment by marvic2409** [comment]
It's all good! I had a while loop with the login flow and it sent over 100 requests to instagram to login. it works fine after waiting 2 minutes
