### ISSUE TITLE
Get total posts by user

### ISSUE THREAD

**Issue by marvic2409** [stanvanrooy/instauto#42]
Is there a way to get the total number of posts by a user?

**Comment by stanvanrooy** [comment]
See https://www.github.com/stanvanrooy/instauto/tree/master/examples%2Fpost%2Fpost_retrieve_by_user.py.

Change the `< 20` comparison to `< math.inf`.

**Comment by stanvanrooy** [comment]
If you want to check for the account used to initiate the client, you can replace the user id search with `self.state.user_id`

**Comment by marvic2409** [comment]
Yep that solved it!
