### ISSUE TITLE
Make `instauto` 3.6+ compatible

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#44]
Should be as simple as removing walrus operators.

**Comment by marvic2409** [comment]
I added a pull request, I believe I have replaced the walrus operators. I have only done a little testing on python3.6 but so far it is working

**Comment by stanvanrooy** [comment]
I'll do a check if that is the only thing that python3.6 doesn't support, but so far so good.

**Comment by d54z** [comment]
i can't upload photos it said information missing

**Comment by stanvanrooy** [comment]
@d54z please open an issue with:
- Your code to construct the `Post` object
- The debug logs

**Comment by d54z** [comment]
> @d54z please open an issue with:
> 
> * Your code to construct the `Post` object
> * The debug logs

i did't really understand
i did as you did
this is my code 
client = ApiClient(user_name=username, password=password)
client.login()
client.save_to_disk('./.instauto.save')

post = ps.Post.create(
    path='./white.png',
    source_type=st.WhereToPost.Feed,
    caption='This is an example. Follow me!'
)

resp = client.post_post(post, 80)
print("Success: ", resp.text)

it says
{"message": "Missing info.", "status": "fail"}

**Comment by stanvanrooy** [comment]
Please put this in a separate issue. https://docs.github.com/en/enterprise/2.15/user/articles/creating-an-issue on how to create an issue.

**Comment by marvic2409** [comment]
I'll try testing out the code on 3.6

**Comment by marvic2409** [comment]
Ok I've tested it out, posting, profile changes, searches, and friendships all work on python 3.6.
