### ISSUE TITLE
Weird get user issue

### ISSUE THREAD

**Issue by marvic2409** [stanvanrooy/instauto#45]
For some reason I get this error when trying to get the number of posts by an instagram user:
`{'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}
Traceback (most recent call last):
  File "insta.py", line 170, in <module>
    main()
  File "insta.py", line 40, in main
    numbr = getsubnums()
  File "insta.py", line 63, in getsubnums
    user = resp['users'][0]
KeyError: 'users'
None
`

I tried waiting 1-2 hours and I still get this error. If this is an issue with the number of requests, wouldn't it be easier to just extract that data from the users page (Where is says Posts: number)?

**Comment by stanvanrooy** [comment]
I was just working on this :). A fix has been pushed to the repo. You can install it by running `pip install git+https://github.com/stanvanrooy/instauto.git --upgrade`
