### ISSUE TITLE
Concern regarding Instagram API changes (Instagram stopping support for legacy APIs on Sep 30th)

### ISSUE THREAD

**Issue by ardalanrazavi** [stanvanrooy/instauto#48]
First I want to thank all the devs working on this great library. Furthermore, seems like Instagram will stop supporting their private API on September 30th (Link: https://www.instagram.com/developer/).

"Legacy API user identifier available on Basic Display API until September 30, 2020"
Seems this means the end of this library usability? Or we can change and adapt which is also not doable from what I have read in their new Instagram Graph API docs... The APIs are very limited and almost only regarding the owner of a page's information (Due to data security concerns). Any thoughts or corrections on my assumption?

**Comment by stanvanrooy** [comment]
This library uses the private API, which is only used in the Instagram app itself. This API is not meant to be used by us, only by Instagram itselfs.

The endpoints `instauto` uses, are extracted from the app.

The article you linked has no effect on this.
