### ISSUE TITLE
Check max length for captions of posts

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#5]
1. Check what the max length is for captions
2. Raise an exception when a caption is passed in, longer than the max_length
3. Add to documentation

**Comment by Marecek460** [comment]
Hi, I would like to do on this feature can u assign it to me please ?

**Comment by Marecek460** [comment]
Hi, I would like to do on this feature can u assign it to me please?

**Comment by stanvanrooy** [comment]
Sure, lmk if you need any help getting set up.
