### ISSUE TITLE
Creat upload story method

### ISSUE THREAD

**Issue by markdrrr** [stanvanrooy/instauto#50]
Creat method  upload image for story

**Comment by stanvanrooy** [comment]
This functionality should already be available. Use `WhereToPost.Story` instead of `WhereToPost.Feed`.

It hasn't been tested. Please re-open if that doesn't work.

**Comment by markdrrr** [comment]
![image](https://user-images.githubusercontent.com/56235826/94285610-916aef80-ff5c-11ea-9cc4-74a7f26a7f79.png)
@stanvanrooy use WhereToPost.Story don't work

**Comment by markdrrr** [comment]
I also tried using  ` st.WhereToPost.story`  image uploaded to feed. 
How to do it right?

**Comment by stanvanrooy** [comment]
will check this later tonight or tomorrow.

**Comment by markdrrr** [comment]
@stanvanrooy Get a fix for upload story method?

**Comment by stanvanrooy** [comment]
@markdrrr please take a look at the updated examples. Lmk if something doesn't work.

**Comment by stanvanrooy** [comment]
I believe, out the top of my head, it is `Whereto post.story`
-------- Oorspronkelijk bericht --------Van: markdrrr ***@***.***> Datum: 25-09-2020  17:26  (GMT+01:00) Aan: stanvanrooy/instauto ***@***.***> Cc: Stan van Rooy ***@***.***>, Mention ***@***.***> Onderwerp: Re: [stanvanrooy/instauto] Creat upload story method (#50) 

@stanvanrooy use WhereToPost.Story don't work
