### ISSUE TITLE
client.followers_get has no attribute 'max_id'

### ISSUE THREAD

**Issue by Danielohayon** [stanvanrooy/instauto#55]
client.followers_get(f) now throws an exception because "GetFollowers" doesn't have "max_id" attribute anymore.

f = fs.GetFollowers(user_id="2283025667")
obj, result = client.followers_get(f)

AttributeError Traceback (most recent call last)
in 
1 f = fs.GetFollowers(user_id=user_id)
----> 2 obj, result = client.followers_get(f)

/opt/anaconda2/envs/Instabot2/lib/python3.8/site-packages/instauto/api/actions/friendships.py in followers_get(self, obj)
65 ```
66 """
---> 67 if obj.max_id is None and obj.page > 0:
68 return obj, False
69 query_params = {

AttributeError: 'GetBase' object has no attribute 'max_id'

due to changes in #54 
https://github.com/stanvanrooy/instauto/commit/468302ad928b7641abf9f209e245d61f7c829ff9#r42655264

**Comment by stanvanrooy** [comment]
I'll publish a fix later today. Weird the linter didn't pick this up in the automated test.

I'll try and find some time to implement some unittests, that's long past due :),
