### ISSUE TITLE
can't share a post

### ISSUE THREAD

**Issue by d54z** [stanvanrooy/instauto#56]
i can really share a post

this is my code
```python
client = ApiClient(user_name=os.environ.get("INSTAUTO_USER") or "your_username", password=os.environ.get("INSTAUTO_PASS") or "your_password")
 client.login()
 client.save_to_disk('./.instauto.save')
 post = ps.Post.create(
        path='./black_square.jpg',
        source_type=st.WhereToPost.Feed,
        caption='This is an example. Follow me!'
    )

 resp = client.post_post(post, 80)
 print("Success: ", resp.ok)
```

Output:
```{"message": "Missing info.", "status": "fail"}```

**Comment by stanvanrooy** [comment]
Does `./black_square.jpg` point to an image on your machine?

**Comment by marvic2409** [comment]
Put this at the start of your code and then put the output here (Remove any usernames/passwords if they get printed):
```
import logging
logging.basicConfig()
logging.getLogger('').setLevel(logging.DEBUG)
```

**Comment by d54z** [comment]
i put this under Client(username,password)
and it make a infinity genreating numbers and letters

**Comment by d54z** [comment]
DEBUG:instagram_private_api.client:REQUEST: https://i.instagram.com/api/v1/si/fetch_headers/?challenge_type=signup&guid=fc591f39fe6511ea81fd4cedfbca2655 POST
DEBUG:instagram_private_api.client:DATA: b''
DEBUG:instagram_private_api.client:REQUEST: https://i.instagram.com/api/v1/accounts/login/ POST
DEBUG:instagram_private_api.client:DATA: b'ig_sig_key_version=4&signed_body=bbcf09ddc08c918d16750f7fb267357d9bfa4926021e96b255835d2a02e5ea52.%7B%22device_id%22%3A%22android-fc58f847fe6511ea%22%2C%22guid%22%3A%22fc58f846-fe65-11ea-8daa-4cedfbca2655%22%2C%22adid%22%3A%22522ac724-9553-0f68-4db4-dac0e73d9280%22%2C%22phone_id%22%3A%22fb885ab7-2ef5-43a0-f59e-2b92643f7e34%22%2C%22_csrftoken%22%3A%22luMi4CSdD9n6DwoBhfVzgJccpBSD1Hle%22%2C%22username%22%3A%223zzmn.memes.test%22%2C%22password%22%3A%223zzmn3zzmn%22%2C%22login_attempt_count%22%3A%220%22%7D'
DEBUG:instagram_private_api.client:USERAGENT: Instagram 76.0.0.15.395 Android (24/7.0; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US; 138226743)
INFO:instauto.api.client:No state provided. Logging in...
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com:443
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "GET /api/v1/zr/token/result/?device_id=android-004c4d37a4533c79&token_hash=&custom_device_id=f3b1765e-004c-4d37-a453-3c7952af4f52&fetch_reason=token_expired HTTP/1.1" 200 203
DEBUG:instauto.api.actions.request:Sent request to https://i.instagram.com/api/v1/zr/token/result/?device_id=android-004c4d37a4533c79&token_hash=&custom_device_id=f3b1765e-004c-4d37-a453-3c7952af4f52&fetch_reason=token_expired, method: GET with data:
 {}
DEBUG:instauto.api.actions.request:******************** START REQUEST ********************
METHOD: GET
URL: https://i.instagram.com/api/v1/zr/token/result/?device_id=android-004c4d37a4533c79&token_hash=&custom_device_id=f3b1765e-004c-4d37-a453-3c7952af4f52&fetch_reason=token_expired
DATA: {}
HEADERS: {'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL', 'accept-encoding': 'gzip, deflate', 'x-fb-http-engine': 'Liger', 'x-ig-connection-speed': '2383kbps', 'x-ig-bandwidth-speed-kbps': '1778.181', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0'}
RESPONSE: b'{"token": {"carrier_name": "", "carrier_id": 0, "ttl": 72000, "features": [], "request_time": 1600952458, "token_hash": "", "rewrite_rules": [], "enabled_wallet_defs_keys": [], "deadline": "", "zero_cms_fetch_interval_seconds": 86400, "carrier_signal_config": []}, "status": "ok"}'
******************** END REQUEST ********************
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/qe/sync/ HTTP/1.1" 200 648
DEBUG:instauto.api.actions.request:Sent request to https://i.instagram.com/api/v1/qe/sync/, method: POST with data: 
 {'_csrftoken': '3SzFK7ERDk9mkW6fRLE9N6reoj0iJW4Z', 'id': 'f3b1765e-004c-4d37-a453-3c7952af4f52', 'sever_config_retrieval': '1', 'experiments': 'ig_android_device_detection_info_upload,ig_android_gmail_oauth_in_reg,ig_android_account_linking_upsell_universe,ig_android_direct_main_tab_universe_v2,ig_android_sign_in_help_only_one_account_family_universe,ig_android_sms_retriever_backtest_universe,ig_android_vc_interop_use_test_igid_universe,ig_android_direct_add_direct_to_android_native_photo_share_sheet,ig_growth_android_profile_pic_prefill_with_fb_pic_2,ig_account_identity_logged_out_signals_global_holdout_universe,ig_android_notification_unpack_universe,ig_android_quickcapture_keep_screen_on,ig_android_device_based_country_verification,ig_android_login_identifier_fuzzy_match,ig_android_reg_modularization_universe,ig_android_video_render_codec_low_memory_gc,ig_android_device_verification_separate_endpoint,ig_android_email_fuzzy_matching_universe,ig_android_suma_landing_page,ig_android_smartlock_hints_universe,ig_android_video_ffmpegutil_pts_fix,ig_android_multi_tap_login_new,ig_android_retry_create_account_universe,ig_android_caption_typeahead_fix_on_o_universe,ig_android_enable_keyboardlistener_redesign,ig_android_reg_nux_headers_cleanup_universe,ig_android_get_cookie_with_concurrent_session_universe,ig_android_nux_add_email_device,ig_android_device_info_foreground_reporting,ig_android_shortcuts_2019,ig_android_device_verification_fb_signup,ig_android_passwordless_account_password_creation_universe,ig_android_black_out_toggle_universe,ig_video_debug_overlay,ig_android_ask_for_permissions_on_reg,ig_assisted_login_universe,ig_android_security_intent_switchoff,ig_android_recovery_one_tap_holdout_universe,ig_android_sim_info_upload,ig_android_mobile_http_flow_device_universe,ig_android_fb_account_linking_sampling_freq_universe,ig_android_access_flow_prefill'}
DEBUG:instauto.api.actions.request:******************** START REQUEST ********************
METHOD: POST
URL: https://i.instagram.com/api/v1/qe/sync/
DATA: {'_csrftoken': '3SzFK7ERDk9mkW6fRLE9N6reoj0iJW4Z', 'id': 'f3b1765e-004c-4d37-a453-3c7952af4f52', 'sever_config_retrieval': '1', 'experiments': 'ig_android_device_detection_info_upload,ig_android_gmail_oauth_in_reg,ig_android_account_linking_upsell_universe,ig_android_direct_main_tab_universe_v2,ig_android_sign_in_help_only_one_account_family_universe,ig_android_sms_retriever_backtest_universe,ig_android_vc_interop_use_test_igid_universe,ig_android_direct_add_direct_to_android_native_photo_share_sheet,ig_growth_android_profile_pic_prefill_with_fb_pic_2,ig_account_identity_logged_out_signals_global_holdout_universe,ig_android_notification_unpack_universe,ig_android_quickcapture_keep_screen_on,ig_android_device_based_country_verification,ig_android_login_identifier_fuzzy_match,ig_android_reg_modularization_universe,ig_android_video_render_codec_low_memory_gc,ig_android_device_verification_separate_endpoint,ig_android_email_fuzzy_matching_universe,ig_android_suma_landing_page,ig_android_smartlock_hints_universe,ig_android_video_ffmpegutil_pts_fix,ig_android_multi_tap_login_new,ig_android_retry_create_account_universe,ig_android_caption_typeahead_fix_on_o_universe,ig_android_enable_keyboardlistener_redesign,ig_android_reg_nux_headers_cleanup_universe,ig_android_get_cookie_with_concurrent_session_universe,ig_android_nux_add_email_device,ig_android_device_info_foreground_reporting,ig_android_shortcuts_2019,ig_android_device_verification_fb_signup,ig_android_passwordless_account_password_creation_universe,ig_android_black_out_toggle_universe,ig_video_debug_overlay,ig_android_ask_for_permissions_on_reg,ig_assisted_login_universe,ig_android_security_intent_switchoff,ig_android_recovery_one_tap_holdout_universe,ig_android_sim_info_upload,ig_android_mobile_http_flow_device_universe,ig_android_fb_account_linking_sampling_freq_universe,ig_android_access_flow_prefill'}    
HEADERS: {'x-cm-bandwidth-kbps': '-1.000', 'x-cm-latency': '-1.000', 'x-ads-opt-out': '0', 'x-ig-app-locale': 'nl_NL', 'x-ig-app-startup-country': 'NL', 'x-ig-device-locale': 'nl_NL', 'x-ig-mapped-locale': 'nl_NL', 'x-ig-connection-speed': '1964kbps', 'x-ig-bandwidth-speed-kbps': '1550.104', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0', 'x-ig-device-id': 'f3b1765e-004c-4d37-a453-3c7952af4f52', 'x-ig-android-id': 'android-004c4d37a4533c79', 'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL, en_US', 'x-mid': 'X2yYigABAAExNQCsB__W4FEUiIp1', 'ig-u-rur': 'VLL', 'accept-encoding': 'gzip', 'x-fb-http-engine': 'Liger', 'authorization': 'Bearer IGT:2:', 'connection': 'close', 'x-pigeon-session-id': 'c5bf45a7-5b83-4c07-ad58-c0afdd47682b', 'x-pigeon-rawclienttime': '1600952459.503', 'x-bloks-version-id': '5da07fc1b20eb4c7d1b2e6146ee5f197072cbbd193d2d1eb3bb4e825d3c39e28', 'x-bloks-is-layout-rtl': 'False', 'host': 'i.instagram.com', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
RESPONSE: b'{"experiments": [{"name": "ig_android_gmail_oauth_in_reg", "group": "rollout_1201", "additional_params": [], "params": [{"name": "try_background_confirm", "value": "true"}]}, {"name": "ig_android_account_linking_upsell_universe", "group": "control", "additional_params": [], "params": [{"name": "logout_impression_limit", "value": "0"}]}, {"name": "ig_android_direct_add_direct_to_android_native_photo_share_sheet", "group": "test", "additional_params": [], "params": [{"name": "is_enabled", "value": "true"}]}, {"name": "ig_android_quickcapture_keep_screen_on", "group": "test", "additional_params": [], "params": [{"name": "keep_screen_on_enabled", "value": "true"}]}, {"name": "ig_android_login_identifier_fuzzy_match", "group": "edit2", "additional_params": [], "params": [{"name": "enabled", "value": "true"}, {"name": "cost", "value": "2"}]}, {"name": "ig_android_video_render_codec_low_memory_gc", "group": "test", "additional_params": [], "params": [{"name": "gc_before_codec_init", "value": "true"}]}, {"name": "ig_android_suma_landing_page", "group": "var1", "additional_params": [], "params": [{"name": "skip_value_prop", "value": "false"}, {"name": "show_generic_icon", "value": "false"}, {"name": "show_title", "value": "false"}]}, {"name": "ig_android_video_ffmpegutil_pts_fix", "group": "control", "additional_params": [], "params": [{"name": "retry_count", "value": "1"}]}, {"name": "ig_android_multi_tap_login_new", "group": "test", "additional_params": [], "params": [{"name": "show_logged_out_only", "value": "true"}, {"name": "enabled", "value": "true"}]}, {"name": "ig_android_get_cookie_with_concurrent_session_universe", "group": "test", "additional_params": [], "params": [{"name": "is_enabled", "value": "true"}]}, {"name": "ig_android_passwordless_account_password_creation_universe", "group": "test_one_tap_check_box_hidden", "additional_params": [], "params": [{"name": "show_save_password_checkbox", "value": "true"}, {"name": "upsell_for_mac_flow", "value": "false"}]}, {"name": "ig_android_security_intent_switchoff", "group": "allusers", "additional_params": [], "params": [{"name": "switch_offs", "value": ""}]}, {"name": "ig_android_sim_info_upload", "group": "test", "additional_params": [], "params": [{"name": "enable_upload", "value": "true"}]}, {"name": "ig_android_fb_account_linking_sampling_freq_universe", "group": 
"control", "additional_params": [], "params": [{"name": "freq", "value": "100"}]}, {"name": "ig_android_access_flow_prefill", "group": "launch", "additional_params": [], "params": [{"name": "is_enabled", "value": "true"}, {"name": "long_timeout", "value": "true"}]}], "status": "ok"}'
******************** END REQUEST ********************

**Comment by d54z** [comment]
then it make auto genretaing alot of number and letters

**Comment by d54z** [comment]
> Does `./black_square.jpg` point to an image on your machine?

yes

**Comment by stanvanrooy** [comment]
Could you include the full log? Including the letters and numbers 
(that's probably the image).

This log does not include the actual request to upload & configure the image, so I can't do much with it.

**Comment by marvic2409** [comment]
If the logs are too long to copy from terminal you can change the logging code to
```
import logging
logging.basicConfig(filename='app.log', filemode='w')
logging.getLogger('').setLevel(logging.DEBUG)
```
and then just upload the file here (after removing your username/passwords)

**Comment by CombatCode** [comment]
Same issue here on version 0.0.15, there is full log:
```
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /rupload_igphoto/1601745701.2885697_0_1520766894 HTTP/1.1" 400 103
DEBUG:instauto.api.actions.request:Sent request to https://i.instagram.com/rupload_igphoto/1601745701.2885697_0_1520766894, method: POST with data: 
 b'\x89PNG\r\n << CUTTED IMAGE >>'
HEADERS: 
{'x-cm-bandwidth-kbps': '-1.000', 'x-cm-latency': '-1.000', 'x-ads-opt-out': '0', 'x-ig-app-locale': 'nl_NL', 'x-ig-app-startup-country': 'NL', 'x-ig-device-locale': 'nl_NL', 'x-ig-mapped-locale': 'nl_NL', 'x-ig-connection-speed': '1533kbps', 'x-ig-bandwidth-speed-kbps': '3833.970', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0', 'x-ig-device-id': 'e9ccf31d-5415-49e0-87e5-6c17b7de7b07', 'x-ig-android-id': 'android-541549e087e56c17', 'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL, en_US', 'x-mid': 'X3iq5AABAAE2zjY8lMGOUfwwJxms', 'ig-u-rur': 'FRC', 'accept-encoding': 'gzip', 'x-fb-http-engine': 'Liger', 'authorization': 'Bearer IGT:2:eyJkc191c2VyX2lkIjoiMjc2MDk3NTMwMzIiLCJzZXNzaW9uaWQiOiIyNzYwOTc1MzAzMiUzQUJNU2NjNU9UNGhnVkc4JTNBMiIsInNob3VsZF91c2VfaGVhZGVyX292ZXJfY29va2llcyI6ZmFsc2V9', 'connection': 'close', 'x-pigeon-session-id': 'b879a1ac-773d-447d-8eab-6341d66be14f', 'x-pigeon-rawclienttime': '1601745701.291', 'x-bloks-version-id': '5da07fc1b20eb4c7d1b2e6146ee5f197072cbbd193d2d1eb3bb4e825d3c39e28', 'x-bloks-is-layout-rtl': 'False', 'host': 'i.instagram.com', 'x-fb-photo-waterfall-id': '35e9ec17-5eda-4c23-8ecb-78fc30666aa8', 'x-entity-length': '674855', 'x-entity-name': '1601745701.2885697_0_1520766894', 'x-instagram-rupload-params': '
{"upload_id": "1601745701.2885697", "media_type": 1, "retry_context": "
{\\"num_reupload\\": 0, \\"num_step_auto_retry\\": 0, \\"num_step_manual_retry\\": 0}", "xsharing_user_ids": "[]", "image_compression": "
{\\"lib_name\\": \\"moz\\", \\"lib_version\\": \\"3.1.m\\", \\"quality\\": \\"80\\"}"}', 'x-entity-type': 'image//tmp_sc', 'offset': '0', 'scene_capture_type': 'standard', 'creation_logger_session_id': 'e84e2ab5-9921-4751-b97e-1a957ebf53e5', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
RESPONSE: b'
{"debug_info":
{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}'
******************** END REQUEST ********************
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 400 46
DEBUG:instauto.api.actions.request:Sent request to https://i.instagram.com/api/v1/media/configure/, method: POST with data: 
 
 {'ig_sig_key_version': '4', 'signed_body': 'SIGNATURE.
 {"scene_capture_type": "", "timezone_offset": "0", "media_folder": "Pictures", "source_type": "4", "device_id": "e9ccf31d-5415-49e0-87e5-6c17b7de7b07", "caption": "This is an example. Follow me!", "upload_id": "1601745701.2885697", "suggested_venue_position": -1, "device": 
 {"manufacturer": "samsung", "model": "beyond1", "android_version": 29, "android_release": "10"}, "edits": 
 {"crop_original_size": [722, 1052], "crop_center": [0.0, 0.0], "crop_zoom": 1.0}, "extra": 
 {"source_width": 722, "source_height": 1052}, "is_suggested_venue": false, "multi_sharing": "-1", "_uid": "27609753032", "_uuid": "2cfb9ee8-1420-4e2e-abd2-6f36823405e2", "_csrftoken": "pVtnSR51QAKxvg6KUG8Lf2V1tcr9h1Sw"}'}
DEBUG:instauto.api.actions.request:******************** START REQUEST ********************
METHOD: POST
URL: https://i.instagram.com/api/v1/media/configure/
DATA: 
{'ig_sig_key_version': '4', 'signed_body': 'SIGNATURE.
{"scene_capture_type": "", "timezone_offset": "0", "media_folder": "Pictures", "source_type": "4", "device_id": "e9ccf31d-5415-49e0-87e5-6c17b7de7b07", "caption": "This is an example. Follow me!", "upload_id": "1601745701.2885697", "suggested_venue_position": -1, "device": 
{"manufacturer": "samsung", "model": "beyond1", "android_version": 29, "android_release": "10"}, "edits": 
{"crop_original_size": [722, 1052], "crop_center": [0.0, 0.0], "crop_zoom": 1.0}, "extra": 
{"source_width": 722, "source_height": 1052}, "is_suggested_venue": false, "multi_sharing": "-1", "_uid": "27609753032", "_uuid": "2cfb9ee8-1420-4e2e-abd2-6f36823405e2", "_csrftoken": "pVtnSR51QAKxvg6KUG8Lf2V1tcr9h1Sw"}'}
HEADERS: 
{'x-cm-bandwidth-kbps': '-1.000', 'x-cm-latency': '-1.000', 'x-ads-opt-out': '0', 'x-ig-app-locale': 'nl_NL', 'x-ig-app-startup-country': 'NL', 'x-ig-device-locale': 'nl_NL', 'x-ig-mapped-locale': 'nl_NL', 'x-ig-connection-speed': '2643kbps', 'x-ig-bandwidth-speed-kbps': '1865.416', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0', 'x-ig-device-id': 'e9ccf31d-5415-49e0-87e5-6c17b7de7b07', 'x-ig-android-id': 'android-541549e087e56c17', 'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL, en_US', 'x-mid': 'X3iq5AABAAE2zjY8lMGOUfwwJxms', 'ig-u-rur': 'FRC', 'accept-encoding': 'gzip', 'x-fb-http-engine': 'Liger', 'authorization': 'Bearer IGT:2:eyJkc191c2VyX2lkIjoiMjc2MDk3NTMwMzIiLCJzZXNzaW9uaWQiOiIyNzYwOTc1MzAzMiUzQUJNU2NjNU9UNGhnVkc4JTNBMiIsInNob3VsZF91c2VfaGVhZGVyX292ZXJfY29va2llcyI6ZmFsc2V9', 'connection': 'close', 'x-pigeon-session-id': 'b879a1ac-773d-447d-8eab-6341d66be14f', 'x-pigeon-rawclienttime': '1601745702.66', 'x-bloks-version-id': '5da07fc1b20eb4c7d1b2e6146ee5f197072cbbd193d2d1eb3bb4e825d3c39e28', 'x-bloks-is-layout-rtl': 'False', 'host': 'i.instagram.com', 'retry_context': '
{"num_reupload": 0, "num_step_auto_retry": 0, "num_step_manual_retry": 0}', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
RESPONSE: b'
{"message": "Missing info.", "status": "fail"}'
******************** END REQUEST ********************
```

**Comment by marvic2409** [comment]
Please open a new issue @CombatCode
