### ISSUE TITLE
Check max length of comments on posts

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#6]
1. Check what the max length is for comments (most likely the same as captions, captions are also seen as comments, but check anyway)
2. Raise an exception when a comment is passed in, longer than the max_length
3. Add to documentation

**Comment by palo608** [comment]
Hey I want to contribute on this issue, can u assign it to me please ?

**Comment by stanvanrooy** [comment]
Sure, lmk if you need any help getting setup.
