### ISSUE TITLE
Upload image without location don't work 

### ISSUE THREAD

**Issue by markdrrr** [stanvanrooy/instauto#62]
I try to upload a photo without specifying the location, I get an error:
KeyError: 'location'

**Comment by stanvanrooy** [comment]
Please update to the latest version, this had already been fixed.

**Comment by markdrrr** [comment]
i use `instauto      0.0.15`   install from git

![image](https://user-images.githubusercontent.com/56235826/94305500-f41eb400-ff79-11ea-875d-e66e23f3148d.png)

still doesn't work

**Comment by marvic2409** [comment]
Hmm I just tested and can confirm that it should not give you this error on the latest version. Maybe try a fresh install?
