### ISSUE TITLE
Create Like Object: TypeError: __init__() missing 1 required positional argument: 'feed_position'

### ISSUE THREAD

**Issue by Samu1808** [stanvanrooy/instauto#79]
**Bug**
When creating a Like object with Like(media_id=*example media id*) you get the Error:

![image](https://user-images.githubusercontent.com/64809910/96045940-fdad8480-0e72-11eb-9fac-ea0729c4da58.png)

**My Solution**
I added in \instauto\api\actions\structs\post.py

![image](https://user-images.githubusercontent.com/64809910/96046144-4cf3b500-0e73-11eb-82d4-7a46ff1fc5cb.png)

So feed_postion isn't required when calling the _Base.__init()__
Please fix this in the repository, if this not going to cause other errors!

**Additional**
Also please update the example Folder t structs.
You can't call like = Like.create(media_id) anymore, but you have to create a normal instance i.e like = Like(media_id), same with Posts!
Thanks for your work <3

**Comment by stanvanrooy** [comment]
Thanks for the report. Feel free to submit a pr ;)

If not, I'll probably fix this like tomorrow or something like that.
