### ISSUE TITLE
Implement method for retrieving posts from your feed, including pagination

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#8]
- [x] Implement method, should probably be added to the post-action, something like `PostRetrieveByFeed`. Add in pagination functionality, like PostRetrieveByUser
- [x] Write test
- [x] Add an example to examples

**Comment by CaiusBonus** [comment]
Hi, I would like to do on this feature can u assign it to me please ?

**Comment by stanvanrooy** [comment]
Let me know if you need any help getting set up, or if you run in to anything. Happy to assist.

You can use the classes within 'api.actions.structs.friendships` for a reference on how to add any new structs you need(all others still need to be updated).

**Comment by marosgonda** [comment]
Hi, I spent some time on it and I am little confused about that what exactly is PostRetrieveByFeed, which endpoint give me required content ?

**Comment by stanvanrooy** [comment]
I don't know which endpoint that is. What I meant, is that the user facing part of it should be similar to `PostRetrieveByFeed`, so users should be able to do this:

```python
    result = client.post_retrieve_from_feed()
    retrieved_items = []

    # retrieve the first 20 posts
    while result and len(retrieved_items) < 20:
        retrieved_items.extend(result)
        result = client.post_retrieve_from_feed()
```
