### ISSUE TITLE
Upload to story with decoration

### ISSUE THREAD

**Issue by stanvanrooy** [stanvanrooy/instauto#88]
This is probably complex if you look at all the different ways you can put text, emojis, gifs, etc. on images posted to a story. 

I'm not sure yet if this is feasible/necessary to implement. The gain might not be worth the effort, although it would be cool to have :)

**Comment by cheersgocheersgo** [comment]
@stanvanrooy   Hello, [https://github.com/stanvanrooy/instauto/issues/76](url) When can this problem be solved? I am looking forward to your reply..
