### ISSUE TITLE
Like: "TypeError: Object of type function is not JSON serializable"

### ISSUE THREAD

**Issue by Samu1808** [stanvanrooy/instauto#91]
**Describe the bug**
When you trying to like posts, you get following Error: 

![image](https://user-images.githubusercontent.com/64809910/97109457-a3fb5480-16d3-11eb-9e41-5e4ba303b941.png)

**Debug output**
I printed out *data* before it will turned into JSON and this was the output:
![image](https://user-images.githubusercontent.com/64809910/97109556-2e43b880-16d4-11eb-9db6-608896ed96c2.png)

so as you can see the lambda functions are still not resolved and they can not be turned into JSON

**Solution**
After browsing through the code I found out, that you have to modify the code as followed to make like work again.

In file ...\instauto\api\actions\post.py:
![image](https://user-images.githubusercontent.com/64809910/97109662-c346b180-16d4-11eb-9341-606384599cc1.png)

I wanted to make a PR but Im new to github and i dont really know how things work with branches.

**Comment by stanvanrooy** [comment]
Looks good. Creating a pr is pretty simple:

1. Create a fork of this repo. You should be able to do this on the website.

2. Pull the repo to your machine

3. Create a new branch, `91FixLike` or something like that with `git branch 91FixLike`

4. Make the change, commit it and push it to your fork.

5. Then you should be able to create a pr to merge into this repo on the github website. 

Or I can just do it :) let me know.
