### ISSUE TITLE
Can't destroy/create friendship

### ISSUE THREAD

**Issue by Samu1808** [stanvanrooy/instauto#97]
**Describe the bug**
If you try to destroy/create friendships with this code:
![image](https://user-images.githubusercontent.com/64809910/99002359-8e43b700-253c-11eb-9877-535473fa6b81.png)

**Debug output**
This exception is thrown:
![image](https://user-images.githubusercontent.com/64809910/99002069-2f7e3d80-253c-11eb-83c4-2f3f307ab780.png)

data is:
{
'surface': <Surface.profile: 'following_sheet'>,
'radio_type': 'wifi-none',
'_csrftoken': '*removed*',
'_uuid': '*removed*',
'_uid': '*removed*'
}

**Additional context**
I tried to just pop the "surface" out of the dict, that it can be JSON serialized.
But than I get following Exception, and I tried this with different (correct) user ids, that can't be the error:

![image](https://user-images.githubusercontent.com/64809910/99002822-60ab3d80-253d-11eb-8435-2d2082ed2095.png)

**Questions**
Why and how do we need the surface object?
Or should it work without the surface object also and why it doesnt?

**Comment by stanvanrooy** [comment]
Surface is used by Instagram to define where in the app the user account is (un)followed from.

What version of 'instauto' are you running?

**Comment by Samu1808** [comment]
The latest I took instauto from the repo.

**Comment by Samu1808** [comment]
Is it working for you? Maybe i did something wrong 🤔
